### ISSUE TITLE
abbreviations

### ISSUE THREAD

**Issue by HelenaSabel** [HelenaSabel/linguistic_variation#4]
Transform:
- [x] `q<ex>ue</ex>` into `q<am>&#772;</am><ex>ue</ex>`
- [x] `d<ex>eu</ex>s` into `d<am>&#8217;</am><ex>eu</ex>s`
- [x] `p<ex>ro</ex>` into `p<am>&#807;</am><ex>ro</ex>`
- [x] `p<ex>er</ex>` into `p<am>&#818;</am><ex>er</ex>`
- [x] `<ex>us</ex>` into `<am>&#42863;</am><ex>us</ex>`
- [x] `<ex>os</ex>` into `<am>&#42863;</am><ex>os</ex>`
- [x] `s<ex>er</ex>` into `<am>&#7836;</am><ex>ser</ex>`
- [x] `<ex>con</ex>` into `<am>&#42862;</am><ex>con</ex>`
- [x] `p<ex>ri<ex>` into `p<am>&#8305;</am><ex>ri</ex>`
- [x] `q<ex>ui<ex>` into `q<am>&#8305;</am><ex>ui</ex>`
- [x] `<ex>e</ex>` into `<am>&#8266;</am><ex>e</ex>` 
- [x] `<ex>ra</ex>` into `<am rend="superscript">&#969;</am><ex>ra</ex>`
- [x] `<ex>ro</ex>` into `<am>&#8338;</am><ex>ro</ex>`
- [x] `<ex>n</ex>` into `<am>&#772;</am><ex>n</ex>`
- [x] `<ex>&#771;</ex>` into `e<am>&#772;</am><ex>&#771;</ex>`
- [ ] `<ex>or</ex>` into `<am rend="superscript">&#42843;</am><ex>or</ex>`
- [ ] `p<ex>or</ex>` into `p<am>&#8337;</am><ex>or</ex>`
- [x] quan
- [x] qua
- [x] contra
- [ ] er
- [ ] re
- [x] quen
- [x] gua
