### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by HelenaSabel** [HelenaSabel/linguistic_variation#5]
- [ ] Add responsible of each scribal intervention.
- [x] Transform abbreviations to add `<am>` element. 
- [x] Correct spurious white spaces created by pretty printing in `<oXygen/>`. 
- [ ] Figure out how to deal with @cert attributes. 
- [ ] Figure out how to deal with copies of songs in the same witness. 
- [x] Fix overlapping abbreviations.
- [x] Add `<supplied>` to deal with crasis.
- [x] Add `<seg>` inside `<orig>` elements.
